/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 17 04:43:38 GMT 2026
 */

package br.com.kvervandi.geo;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.kvervandi.geo.Main;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Main_ESTest extends Main_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SystemInUtil.addInputLine("-1");
      String[] stringArray0 = new String[2];
      Main.main(stringArray0);
      assertEquals(2, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      SystemInUtil.addInputLine("1");
      SystemInUtil.addInputLine("1");
      SystemInUtil.addInputLine("2. Descobrir \u00E2ngulo (dados 3 lados)");
      String[] stringArray0 = new String[3];
      Main.main(stringArray0);
      assertEquals(3, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[9];
      SystemInUtil.addInputLine(" 2");
      SystemInUtil.addInputLine(" 2");
      SystemInUtil.addInputLine(" 2");
      SystemInUtil.addInputLine(" 2");
      Main.main(stringArray0);
      assertEquals(9, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[1];
      SystemInUtil.addInputLine(" 2");
      SystemInUtil.addInputLine(" 2");
      SystemInUtil.addInputLine(" 2");
      Main.main(stringArray0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[1];
      SystemInUtil.addInputLine("8");
      Main.main(stringArray0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Main.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Main main0 = new Main();
  }
}
