/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 20 01:34:01 GMT 2026
 */

package br.com.kvervandi.geo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.com.kvervandi.geo.CalculadoraGeometrica;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CalculadoraGeometrica_ESTest extends CalculadoraGeometrica_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      double double0 = calculadoraGeometrica0.calcularAngulo(2992.677564932, 2992.677564932, 1816.578182151059);
      assertEquals(72.33182687621816, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(1.0, 2.0, 1.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o forma um tri\u00E2ngulo (Desigualdade Triangular)
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(1.0, 1.0, 2.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o forma um tri\u00E2ngulo (Desigualdade Triangular)
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(2.0, 1.0, 1.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o forma um tri\u00E2ngulo (Desigualdade Triangular)
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(1809.1910204611875, 1809.1910204611875, 0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(11070.53930695252, 0.0, 332.2104629727);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(0.0, 0.0, 0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      double double0 = calculadoraGeometrica0.calcularTerceiroLado(2878.436, 1979.1606, 1979.1606);
      assertEquals(4857.470743196868, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularTerceiroLado(1148.9, 0.0, 0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularTerceiroLado((-1212.157901), 22141.07861390504, (-1212.157901));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      double double0 = calculadoraGeometrica0.calcularTerceiroLado(2.0, 2.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      double double0 = calculadoraGeometrica0.calcularAngulo(7.862903205990667E-5, 22141.5, 22141.5);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(238.158, 2063.481, 238.158);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o forma um tri\u00E2ngulo (Desigualdade Triangular)
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(86.0, 86.0, 22126.966);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o forma um tri\u00E2ngulo (Desigualdade Triangular)
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(2729.57008, 564.5764378, 564.5764378);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o forma um tri\u00E2ngulo (Desigualdade Triangular)
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(321.3076521251485, 321.3076521251485, (-35.86977566168136));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(22974.019132417616, (-1.98803554), 22974.019132417616);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo((-1763.6559869446135), (-1763.6559869446135), (-1763.6559869446135));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularTerceiroLado(2079.212, (-1.0), (-1.0));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularTerceiroLado(0.0, 2884.790392165269, 2884.790392165269);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }
}
