/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 17 04:42:49 GMT 2026
 */

package br.com.kvervandi.geo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.com.kvervandi.geo.CalculadoraGeometrica;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CalculadoraGeometrica_ESTest extends CalculadoraGeometrica_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      double double0 = calculadoraGeometrica0.calcularAngulo(1.9090959104164312E-5, 3829.511996910157, 3829.511996910157);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(1.0, 2.0, 1.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o forma um tri\u00E2ngulo (Desigualdade Triangular)
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(1.0, 1.0, 2.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o forma um tri\u00E2ngulo (Desigualdade Triangular)
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(2.0, 1.0, 1.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o forma um tri\u00E2ngulo (Desigualdade Triangular)
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(622.9, 1904.2494, 0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(1857.0, 0.0, 2425.55062405729);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(0.0, 238.831, 179.0051978547395);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      double double0 = calculadoraGeometrica0.calcularTerceiroLado(2.842596612892361E-8, 0.0012762006955476537, 0.0012762006955476537);
      assertEquals(0.001276172269581532, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularTerceiroLado(631.071, 0.0, 631.071);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularTerceiroLado((-1263.17882), (-1263.17882), (-1263.17882));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      double double0 = calculadoraGeometrica0.calcularTerceiroLado(1977.41347561203, 1977.41347561203, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      double double0 = calculadoraGeometrica0.calcularAngulo(238.831, 119.42, 119.42);
      assertEquals(179.0051978547395, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(23.96693397597406, 175.28793250390996, 23.96693397597406);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o forma um tri\u00E2ngulo (Desigualdade Triangular)
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(15.432521041211917, 15.432521041211917, 3792.89);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o forma um tri\u00E2ngulo (Desigualdade Triangular)
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(1656.3042911089406, 40.624695697636426, 40.624695697636426);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o forma um tri\u00E2ngulo (Desigualdade Triangular)
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(897.405540651657, 897.405540651657, (-3505.5717341489085));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo(13.301176722292922, (-1075.9623278566878), (-1075.9623278566878));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      double double0 = calculadoraGeometrica0.calcularAngulo(2.842596612892361E-8, 0.0012762006955476537, 0.001276172269581532);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularAngulo((-151.91), (-2077.42), 0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularTerceiroLado(0.4153, (-1370.152770178), (-1370.152770178));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CalculadoraGeometrica calculadoraGeometrica0 = new CalculadoraGeometrica();
      // Undeclared exception!
      try { 
        calculadoraGeometrica0.calcularTerceiroLado(0.0, 0.0, 0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Lados devem ser positivos
         //
         verifyException("br.com.kvervandi.geo.CalculadoraGeometrica", e);
      }
  }
}
